### ISSUE TITLE
Create the User Entity

### ISSUE THREAD

**Issue by ThallesT** [Granmilk/vault-bot#5]
The user entity has:

- [x] DiscordId 
- [x] Name
- [x] DiscordTag
- [x] RegisteredAt
- [x] GeneralPassword - crypt
- [x] isAdmin - default false
- [x] GuildId

then create:

- [x] UserProfileRepository
- [x] UserProfileService

**Comment by JohnnatanTomaz** [comment]
Entity, repository and service class created.
