### ISSUE TITLE
Create the PrivateChannel Entity

### ISSUE THREAD

**Issue by ThallesT** [Granmilk/vault-bot#8]
In this entity we will register the:

- [x] PrivateChannelId
- [x] ChannelId 
- [x] GuildId
- [x] UserId
- [x] Password

this entity is the responsible to check the user password for a channel of a guild, so we have to implement the:

- [x] PrivateChannelService
- [x] PrivateChannelRepository

**Comment by JohnnatanTomaz** [comment]
Entity, repository and service class created.
